### PR TITLE
Update for PredictionIO 0.12.0-incubating

### PR DESCRIPTION
**Pull request by takezoe**

### CODE REVIEW

**Review by nlauchande — APPROVED** [review]
LGTM

**Review by abhimanyunagrath — APPROVED** [review]

**Comment by takezoe** [comment]
Sorry, this pull request was not enough to move SparkML. Since I can't do it immediately, once close this pull request.

**Comment by nlauchande** [comment]
Hey @takezoe  i am interested on tackling this task. Can i work on it ?

**Comment by takezoe** [comment]
@nlauchande Sure! It looks to need to fix `Preparator` and `NBAlgorithmParams` additionally.

**Comment by takezoe** [comment]
@nlauchande Sorry, it was easier than my expectation.

I could confirm to work by this fix:
https://github.com/takezoe/incubator-predictionio-template-text-classifier/commit/285da4f0523d155feaf9445fd6cd214883f2c94d

If you didn't start work on it, I would like to recreate pull request.

**Comment by nlauchande** [comment]
@takezoe No problems, please go ahead wouldn't be able to start work on it
today !!

**Comment by takezoe** [comment]
Fixed in #16

**Pull request closed without merging**
