### PR TITLE
Fix use of case class

### PR DESCRIPTION
**Pull request by takezoe**

### CODE REVIEW

**Comment by shimamoto** [comment]
LGTM!

**Comment by hareeshmu** [comment]
How to make this compatible with **PredictionIO-0.12.0-incubating**
Able to build after adding `scalaVersion := "2.11.8"` in the build.sbt 

But` pio train` fails: 
```
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.sql.SQLContext$implicits$.rddToDataFrameHolder(Lorg/apache/spark/rdd/RDD;Lscala/reflect/api/TypeTags$TypeTag;)Lorg/apache/spark/sql/DataFrameHolder;
	at org.example.textclassification.LRAlgorithm.train(LRAlgorithm.scala:37)
	at org.example.textclassification.LRAlgorithm.train(LRAlgorithm.scala:19)
	at org.apache.predictionio.controller.P2LAlgorithm.trainBase(P2LAlgorithm.scala:49)
	at org.apache.predictionio.controller.Engine$$anonfun$18.apply(Engine.scala:690)
	at org.apache.predictionio.controller.Engine$$anonfun$18.apply(Engine.scala:690)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:285)
	at org.apache.predictionio.controller.Engine$.train(Engine.scala:690)
	at org.apache.predictionio.controller.Engine.train(Engine.scala:176)
	at org.apache.predictionio.workflow.CoreWorkflow$.runTrain(CoreWorkflow.scala:67)
	at org.apache.predictionio.workflow.CreateWorkflow$.main(CreateWorkflow.scala:251)
	at org.apache.predictionio.workflow.CreateWorkflow.main(CreateWorkflow.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:743)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

```

**Comment by takezoe** [comment]
@hareeshmu We are progressing updating templates just now, but this template is not updated for PredictionIO 0.12.0 yet. Some code modifications seem to be needed for Spark 2.1.1.

**Comment by hareeshmu** [comment]
Thanks for the update. I will wait for the template to be released for 0.12.0.

**Comment by takezoe** [comment]
@hareeshmu I created a pull request #15 to update this template for PredictionIO 0.12.0.
You can test with PredictionIO 0.12.0 by checkout the branch of this pull request, or wait for a while until this pull request will be merged.

**Comment by hareeshmu** [comment]
Thank you so much! Appreciate your efforts.

**Comment by hareeshmu** [comment]
@takezoe 

PredictionIO 0.12.0.

using emails.json data

While training the modal following error is coming:

```
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: Column features must be of type org.apache.spark.ml.linalg.VectorUDT@3bfc3ba7 but was actually org.apache.spark.mllib.linalg.VectorUDT@f71b0bce.
	at scala.Predef$.require(Predef.scala:224)
	at org.apache.spark.ml.util.SchemaUtils$.checkColumnType(SchemaUtils.scala:42)
	at org.apache.spark.ml.PredictorParams$class.validateAndTransformSchema(Predictor.scala:51)
	at org.apache.spark.ml.classification.Classifier.org$apache$spark$ml$classification$ClassifierParams$$super$validateAndTransformSchema(Classifier.scala:58)
	at org.apache.spark.ml.classification.ClassifierParams$class.validateAndTransformSchema(Classifier.scala:42)
	at org.apache.spark.ml.classification.ProbabilisticClassifier.org$apache$spark$ml$classification$ProbabilisticClassifierParams$$super$validateAndTransformSchema(ProbabilisticClassifier.scala:53)
	at org.apache.spark.ml.classification.ProbabilisticClassifierParams$class.validateAndTransformSchema(ProbabilisticClassifier.scala:37)
	at org.apache.spark.ml.classification.LogisticRegression.org$apache$spark$ml$classification$LogisticRegressionParams$$super$validateAndTransformSchema(LogisticRegression.scala:193)
	at org.apache.spark.ml.classification.LogisticRegressionParams$class.validateAndTransformSchema(LogisticRegression.scala:184)
	at org.apache.spark.ml.classification.LogisticRegression.validateAndTransformSchema(LogisticRegression.scala:193)
	at org.apache.spark.ml.Predictor.transformSchema(Predictor.scala:122)
	at org.apache.spark.ml.PipelineStage.transformSchema(Pipeline.scala:74)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:90)
	at org.example.textclassification.LRAlgorithm$$anonfun$3.apply(LRAlgorithm.scala:50)
	at org.example.textclassification.LRAlgorithm$$anonfun$3.apply(LRAlgorithm.scala:47)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.example.textclassification.LRAlgorithm.train(LRAlgorithm.scala:46)
	at org.example.textclassification.LRAlgorithm.train(LRAlgorithm.scala:17)
	at org.apache.predictionio.controller.P2LAlgorithm.trainBase(P2LAlgorithm.scala:49)
	at org.apache.predictionio.controller.Engine$$anonfun$18.apply(Engine.scala:690)
	at org.apache.predictionio.controller.Engine$$anonfun$18.apply(Engine.scala:690)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:285)
	at org.apache.predictionio.controller.Engine$.train(Engine.scala:690)
	at org.apache.predictionio.controller.Engine.train(Engine.scala:176)
	at org.apache.predictionio.workflow.CoreWorkflow$.runTrain(CoreWorkflow.scala:67)
	at org.apache.predictionio.workflow.CreateWorkflow$.main(CreateWorkflow.scala:251)
	at org.apache.predictionio.workflow.CreateWorkflow.main(CreateWorkflow.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:743)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

```

**Pull request closed without merging**
