### PR TITLE
Mark override methods

### PR DESCRIPTION
**Pull request by takezoe**

### CODE REVIEW

**Comment by shimamoto** [comment]
@takezoe I just wonder if we can maintain this template because only this template is different from other templates. What do you think?

**Comment by takezoe** [comment]
@shimamoto In general, text classification is a common use case of machine learning, so I think it's worth to maintain. However only this template has different structure (and versioning policy) among the official templates, as you said and that is one of pain points in maintenance.

I'm really not sure if we should keep maintaining this template, but if we will keep it, we should do refactoring following other templates.

**Comment by shimamoto** [comment]
@takezoe Definitely. If we continue to maintain this template, we should do refactoring.

**Comment by takezoe** [comment]
@shimamoto Anyway, do you have any concern about this pull request? I think this changes have no negative effect even if we won't keep maintaining this template in the future.

**Comment by shimamoto** [comment]
@takezoe thanks, merging to master!

**Pull request merged**
